# Generated by Django 2.2.1 on 2019-07-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_bg_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blogcount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fields',
            field=models.CharField(default='Personal Blog', max_length=200),
        ),
    ]
