# Generated by Django 2.2.1 on 2019-08-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190804_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('dop', models.DateTimeField()),
                ('post_text', models.CharField(max_length=150)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
