# Generated by Django 2.2.1 on 2019-08-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Pst',
        ),
        migrations.RenameField(
            model_name='pst',
            old_name='post_id',
            new_name='pst_id',
        ),
        migrations.RenameField(
            model_name='pst',
            old_name='post_text',
            new_name='pst_text',
        ),
    ]
