# Generated by Django 2.2.1 on 2019-08-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_pst_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pst',
            name='user',
        ),
    ]
